import { createRoot } from "react-dom/client";
import { RouterProvider } from "@tanstack/react-router";
import { getRouter } from "./router";
import "./styles.css";

import { registerSW } from "virtual:pwa-register";

// === FORCE PURGE CACHE ON VERSION UPDATE ===
const CURRENT_VERSION = "2026-06-19_v1";
if (typeof window !== "undefined") {
  const savedVersion = localStorage.getItem("pwa_version");
  if (savedVersion !== CURRENT_VERSION) {
    console.log(`Wali Santri PWA: Version mismatch (${savedVersion} vs ${CURRENT_VERSION}). Purging caches...`);
    if ("caches" in window) {
      caches.keys().then((keys) => {
        return Promise.all(keys.map((key) => caches.delete(key)));
      }).then(() => {
        localStorage.setItem("pwa_version", CURRENT_VERSION);
        console.log("Wali Santri PWA: Cache purged, restarting...");
        window.location.reload();
      }).catch((err) => {
        console.error("Wali Santri PWA: Purge error", err);
        localStorage.setItem("pwa_version", CURRENT_VERSION);
      });
    } else {
      localStorage.setItem("pwa_version", CURRENT_VERSION);
    }
  }
}
// === END FORCE PURGE CACHE ===

// === PWA Service Worker Registration & Auto-Update/Force-Refresh Logic ===
if (typeof window !== "undefined" && "serviceWorker" in navigator) {
  let refreshing = false;

  // Listen for the controllerchange event to reload the page when a new SW takes control
  navigator.serviceWorker.addEventListener("controllerchange", () => {
    if (refreshing) return;
    refreshing = true;
    console.log("Wali Santri PWA: New service worker active, purging all caches and reloading page to apply update...");
    
    // Purge caches on update to ensure no stale assets are used
    if ("caches" in window) {
      caches.keys().then((keys) => {
        return Promise.all(keys.map((key) => caches.delete(key)));
      }).then(() => {
        window.location.reload();
      }).catch(() => {
        window.location.reload();
      });
    } else {
      window.location.reload();
    }
  });

  // Register the service worker generated by Vite PWA
  const updateSW = registerSW({
    immediate: true,
    onNeedRefresh() {
      console.log("Wali Santri PWA: New content available, force-activating update...");
      updateSW(true);
    },
    onOfflineReady() {
      console.log("Wali Santri PWA: App ready to work offline.");
    },
  });

  // Check for updates in the background every 5 minutes
  setInterval(() => {
    console.log("Wali Santri PWA: Checking for service worker updates...");
    updateSW(true);
  }, 5 * 60 * 1000);
}
// === END PWA Service Worker LOGIC ===

console.log("Wali Santri PWA: Initializing...");

const router = getRouter();

const rootElement = document.getElementById("root");
if (rootElement) {
  try {
    console.log("Wali Santri PWA: Root element found, rendering...");
    const root = createRoot(rootElement);
    root.render(<RouterProvider router={router} />);
  } catch (err) {
    console.error("Wali Santri PWA: Render Error:", err);
  }
} else {
  console.error("Wali Santri PWA: Root element NOT found!");
}
