/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as TahfidzRouteImport } from './routes/tahfidz'
import { Route as TagihanRouteImport } from './routes/tagihan'
import { Route as TabunganRouteImport } from './routes/tabungan'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PrestasiRouteImport } from './routes/prestasi'
import { Route as PetugasRouteImport } from './routes/petugas'
import { Route as PerilakuRouteImport } from './routes/perilaku'
import { Route as NilaiRouteImport } from './routes/nilai'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LimitRouteImport } from './routes/limit'
import { Route as LanjutUnitRouteImport } from './routes/lanjut-unit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlokirSaldoRouteImport } from './routes/blokir-saldo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagihanBillIdRouteImport } from './routes/tagihan_.$billId'
import { Route as PembayaranPayIdRouteImport } from './routes/pembayaran.$payId'
import { Route as BeritaNewsIdRouteImport } from './routes/berita.$newsId'
import { Route as AdminApprovalRouteImport } from './routes/admin.approval'

const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const TahfidzRoute = TahfidzRouteImport.update({
  id: '/tahfidz',
  path: '/tahfidz',
  getParentRoute: () => rootRouteImport,
} as any)
const TagihanRoute = TagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => rootRouteImport,
} as any)
const TabunganRoute = TabunganRouteImport.update({
  id: '/tabungan',
  path: '/tabungan',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestasiRoute = PrestasiRouteImport.update({
  id: '/prestasi',
  path: '/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasRoute = PetugasRouteImport.update({
  id: '/petugas',
  path: '/petugas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerilakuRoute = PerilakuRouteImport.update({
  id: '/perilaku',
  path: '/perilaku',
  getParentRoute: () => rootRouteImport,
} as any)
const NilaiRoute = NilaiRouteImport.update({
  id: '/nilai',
  path: '/nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitRoute = LimitRouteImport.update({
  id: '/limit',
  path: '/limit',
  getParentRoute: () => rootRouteImport,
} as any)
const LanjutUnitRoute = LanjutUnitRouteImport.update({
  id: '/lanjut-unit',
  path: '/lanjut-unit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlokirSaldoRoute = BlokirSaldoRouteImport.update({
  id: '/blokir-saldo',
  path: '/blokir-saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagihanBillIdRoute = TagihanBillIdRouteImport.update({
  id: '/tagihan_/$billId',
  path: '/tagihan/$billId',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranPayIdRoute = PembayaranPayIdRouteImport.update({
  id: '/pembayaran/$payId',
  path: '/pembayaran/$payId',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaNewsIdRoute = BeritaNewsIdRouteImport.update({
  id: '/berita/$newsId',
  path: '/berita/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalRoute = AdminApprovalRouteImport.update({
  id: '/admin/approval',
  path: '/admin/approval',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blokir-saldo': typeof BlokirSaldoRoute
  '/dashboard': typeof DashboardRoute
  '/lanjut-unit': typeof LanjutUnitRoute
  '/limit': typeof LimitRoute
  '/login': typeof LoginRoute
  '/nilai': typeof NilaiRoute
  '/perilaku': typeof PerilakuRoute
  '/petugas': typeof PetugasRoute
  '/prestasi': typeof PrestasiRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/tabungan': typeof TabunganRoute
  '/tagihan': typeof TagihanRoute
  '/tahfidz': typeof TahfidzRoute
  '/topup': typeof TopupRoute
  '/admin/approval': typeof AdminApprovalRoute
  '/berita/$newsId': typeof BeritaNewsIdRoute
  '/pembayaran/$payId': typeof PembayaranPayIdRoute
  '/tagihan/$billId': typeof TagihanBillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blokir-saldo': typeof BlokirSaldoRoute
  '/dashboard': typeof DashboardRoute
  '/lanjut-unit': typeof LanjutUnitRoute
  '/limit': typeof LimitRoute
  '/login': typeof LoginRoute
  '/nilai': typeof NilaiRoute
  '/perilaku': typeof PerilakuRoute
  '/petugas': typeof PetugasRoute
  '/prestasi': typeof PrestasiRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/tabungan': typeof TabunganRoute
  '/tagihan': typeof TagihanRoute
  '/tahfidz': typeof TahfidzRoute
  '/topup': typeof TopupRoute
  '/admin/approval': typeof AdminApprovalRoute
  '/berita/$newsId': typeof BeritaNewsIdRoute
  '/pembayaran/$payId': typeof PembayaranPayIdRoute
  '/tagihan/$billId': typeof TagihanBillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blokir-saldo': typeof BlokirSaldoRoute
  '/dashboard': typeof DashboardRoute
  '/lanjut-unit': typeof LanjutUnitRoute
  '/limit': typeof LimitRoute
  '/login': typeof LoginRoute
  '/nilai': typeof NilaiRoute
  '/perilaku': typeof PerilakuRoute
  '/petugas': typeof PetugasRoute
  '/prestasi': typeof PrestasiRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/tabungan': typeof TabunganRoute
  '/tagihan': typeof TagihanRoute
  '/tahfidz': typeof TahfidzRoute
  '/topup': typeof TopupRoute
  '/admin/approval': typeof AdminApprovalRoute
  '/berita/$newsId': typeof BeritaNewsIdRoute
  '/pembayaran/$payId': typeof PembayaranPayIdRoute
  '/tagihan_/$billId': typeof TagihanBillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blokir-saldo'
    | '/dashboard'
    | '/lanjut-unit'
    | '/limit'
    | '/login'
    | '/nilai'
    | '/perilaku'
    | '/petugas'
    | '/prestasi'
    | '/profil'
    | '/riwayat'
    | '/tabungan'
    | '/tagihan'
    | '/tahfidz'
    | '/topup'
    | '/admin/approval'
    | '/berita/$newsId'
    | '/pembayaran/$payId'
    | '/tagihan/$billId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blokir-saldo'
    | '/dashboard'
    | '/lanjut-unit'
    | '/limit'
    | '/login'
    | '/nilai'
    | '/perilaku'
    | '/petugas'
    | '/prestasi'
    | '/profil'
    | '/riwayat'
    | '/tabungan'
    | '/tagihan'
    | '/tahfidz'
    | '/topup'
    | '/admin/approval'
    | '/berita/$newsId'
    | '/pembayaran/$payId'
    | '/tagihan/$billId'
  id:
    | '__root__'
    | '/'
    | '/blokir-saldo'
    | '/dashboard'
    | '/lanjut-unit'
    | '/limit'
    | '/login'
    | '/nilai'
    | '/perilaku'
    | '/petugas'
    | '/prestasi'
    | '/profil'
    | '/riwayat'
    | '/tabungan'
    | '/tagihan'
    | '/tahfidz'
    | '/topup'
    | '/admin/approval'
    | '/berita/$newsId'
    | '/pembayaran/$payId'
    | '/tagihan_/$billId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlokirSaldoRoute: typeof BlokirSaldoRoute
  DashboardRoute: typeof DashboardRoute
  LanjutUnitRoute: typeof LanjutUnitRoute
  LimitRoute: typeof LimitRoute
  LoginRoute: typeof LoginRoute
  NilaiRoute: typeof NilaiRoute
  PerilakuRoute: typeof PerilakuRoute
  PetugasRoute: typeof PetugasRoute
  PrestasiRoute: typeof PrestasiRoute
  ProfilRoute: typeof ProfilRoute
  RiwayatRoute: typeof RiwayatRoute
  TabunganRoute: typeof TabunganRoute
  TagihanRoute: typeof TagihanRoute
  TahfidzRoute: typeof TahfidzRoute
  TopupRoute: typeof TopupRoute
  AdminApprovalRoute: typeof AdminApprovalRoute
  BeritaNewsIdRoute: typeof BeritaNewsIdRoute
  PembayaranPayIdRoute: typeof PembayaranPayIdRoute
  TagihanBillIdRoute: typeof TagihanBillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahfidz': {
      id: '/tahfidz'
      path: '/tahfidz'
      fullPath: '/tahfidz'
      preLoaderRoute: typeof TahfidzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagihan': {
      id: '/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof TagihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabungan': {
      id: '/tabungan'
      path: '/tabungan'
      fullPath: '/tabungan'
      preLoaderRoute: typeof TabunganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestasi': {
      id: '/prestasi'
      path: '/prestasi'
      fullPath: '/prestasi'
      preLoaderRoute: typeof PrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas': {
      id: '/petugas'
      path: '/petugas'
      fullPath: '/petugas'
      preLoaderRoute: typeof PetugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perilaku': {
      id: '/perilaku'
      path: '/perilaku'
      fullPath: '/perilaku'
      preLoaderRoute: typeof PerilakuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nilai': {
      id: '/nilai'
      path: '/nilai'
      fullPath: '/nilai'
      preLoaderRoute: typeof NilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limit': {
      id: '/limit'
      path: '/limit'
      fullPath: '/limit'
      preLoaderRoute: typeof LimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanjut-unit': {
      id: '/lanjut-unit'
      path: '/lanjut-unit'
      fullPath: '/lanjut-unit'
      preLoaderRoute: typeof LanjutUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blokir-saldo': {
      id: '/blokir-saldo'
      path: '/blokir-saldo'
      fullPath: '/blokir-saldo'
      preLoaderRoute: typeof BlokirSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagihan_/$billId': {
      id: '/tagihan_/$billId'
      path: '/tagihan/$billId'
      fullPath: '/tagihan/$billId'
      preLoaderRoute: typeof TagihanBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran/$payId': {
      id: '/pembayaran/$payId'
      path: '/pembayaran/$payId'
      fullPath: '/pembayaran/$payId'
      preLoaderRoute: typeof PembayaranPayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$newsId': {
      id: '/berita/$newsId'
      path: '/berita/$newsId'
      fullPath: '/berita/$newsId'
      preLoaderRoute: typeof BeritaNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approval': {
      id: '/admin/approval'
      path: '/admin/approval'
      fullPath: '/admin/approval'
      preLoaderRoute: typeof AdminApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlokirSaldoRoute: BlokirSaldoRoute,
  DashboardRoute: DashboardRoute,
  LanjutUnitRoute: LanjutUnitRoute,
  LimitRoute: LimitRoute,
  LoginRoute: LoginRoute,
  NilaiRoute: NilaiRoute,
  PerilakuRoute: PerilakuRoute,
  PetugasRoute: PetugasRoute,
  PrestasiRoute: PrestasiRoute,
  ProfilRoute: ProfilRoute,
  RiwayatRoute: RiwayatRoute,
  TabunganRoute: TabunganRoute,
  TagihanRoute: TagihanRoute,
  TahfidzRoute: TahfidzRoute,
  TopupRoute: TopupRoute,
  AdminApprovalRoute: AdminApprovalRoute,
  BeritaNewsIdRoute: BeritaNewsIdRoute,
  PembayaranPayIdRoute: PembayaranPayIdRoute,
  TagihanBillIdRoute: TagihanBillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
